// Generated by CoffeeScript 2.5.1
import backendless from 'backendless';

export default function(Vue, {apiId, apiKey}) {
  backendless.initApp(apiId, apiKey);
  return Vue.prototype.$backendless = backendless;
};
