// Generated by CoffeeScript 2.5.0
import backendless from 'backendless';

export default function(Vue, options) {
  backendless.initApp(options.apiId, options.apiKey);
  return Vue.prototype.$bl = backendless;
};
