// Generated by CoffeeScript 2.4.1
(function() {
  var nodeExternals;

  nodeExternals = require('webpack-node-externals');

  module.exports = function(api) {
    api.chainWebpack(function(server, {isServer}) {
      if (isServer) {
        return server.externals([
          nodeExternals({
            whitelist: [/^vuetify/]
          })
        ]);
      }
    });
    return api.loadSource(function(store) {});
  };

  // // Use the Data store API here: https://gridsome.org/docs/data-store-api

}).call(this);
