// Generated by CoffeeScript 2.4.1
(function() {
  var nodeExternals;

  nodeExternals = require('webpack-node-externals');

  // axios = require 'axios'
  module.exports = function(api) {
    return api.chainWebpack(function(server, {isServer}) {
      if (isServer) {
        return server.externals([
          nodeExternals({
            whitelist: [/^vuetify/,
          /\.(c|sa)ss$/]
          })
        ]);
      }
    });
  };

}).call(this);
