// Generated by CoffeeScript 2.4.1
(function() {
  var axios, nodeExternals;

  nodeExternals = require('webpack-node-externals');

  axios = require('axios');

  module.exports = function(api) {
    api.chainWebpack(function(server, {isServer}) {
      if (isServer) {
        return server.externals([
          nodeExternals({
            whitelist: [/^vuetify/,
          /\.css$/]
          })
        ]);
      }
    });
    return api.loadSource(async function({addCollection}) {
      var collection, data, i, item, len, results;
      ({data} = (await axios.get('http://localhost:1337/personnes')));
      // console.log typeof addCollection
      collection = addCollection('Personnes');
      results = [];
      for (i = 0, len = data.length; i < len; i++) {
        item = data[i];
        results.push(collection.addNode(item));
      }
      return results;
    });
  };

  // api.loadSource (actions) ->
// 	console.log 'addCollection: ', actions.addCollection

}).call(this);
