// Generated by CoffeeScript 2.5.1
import Vuetify from 'vuetify/lib';

import 'vuetify/dist/vuetify.min.css';

import '@mdi/font/css/materialdesignicons.css';

export default function(Vue, options, {head}) {
  Vue.use(Vuetify);
  return head.link.push({
    href: 'https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900',
    rel: 'stylesheet'
  });
};
