// Generated by CoffeeScript 2.5.1
(function() {
  module.exports = function({configureWebpack}) {
    return configureWebpack({
      plugins: [new (require('vuetify-loader/lib/plugin'))()]
    });
  };

}).call(this);
