// Generated by CoffeeScript 2.4.1
import Vuetify from 'vuetify';

import 'vuetify/dist/vuetify.min.css';

import '@mdi/font/css/materialdesignicons.css';

import colors from 'vuetify/lib/util/colors';

export default function(Vue, options, {appOptions, head}) {
  Vue.use(Vuetify);
  appOptions.vuetify = new Vuetify(options);
  return head.link.push({
    href: 'https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900',
    rel: 'stylesheet'
  });
};
