// Generated by CoffeeScript 2.4.1
(function() {
  module.exports = function({configureWebpack}) {
    return configureWebpack(function(config) {
      config.plugins.push(new (require('vuetify-loader/lib/plugin'))({
        progressiveImages: true
      }));
      return config;
    });
  };

}).call(this);
