// Generated by CoffeeScript 2.5.0
(function() {
  module.exports = function({configureWebpack}) {
    return configureWebpack(function(config) {
      console.log(JSON.stringify(config, null, '  '));
      return config;
    });
  };

}).call(this);
