// Generated by CoffeeScript 2.5.0
(function() {
  module.exports = function({chainWebpack, configureWebpack}) {
    chainWebpack(function(config) {
      return config.module.rule('coffee').test(/\.coffee$/).use('coffee-loader').loader('coffee-loader');
    });
    return configureWebpack(function(config) {
      config.resolve.extensions.unshift('.coffee');
      return config;
    });
  };

}).call(this);
