// Generated by CoffeeScript 2.5.1
(function() {
  module.exports = function({configureWebpack}) {
    return configureWebpack({
      module: {
        rules: [
          {
            test: /\.coffee$/,
            use: 'coffee-loader'
          }
        ]
      },
      resolve: {
        extensions: ['.coffee']
      }
    });
  };

}).call(this);
