// Generated by CoffeeScript 2.5.1
import Commerce from '@chec/commerce.js';

export default function(Vue, {apiKey, consoleDebugger}) {
  return Vue.prototype.$commerce = new Commerce(apiKey, consoleDebugger);
};
