// Generated by CoffeeScript 2.5.1
;(function() {
	module.exports = function({ configureWebpack }) {
		return configureWebpack(function(config) {
			var i, j, k, len, len1, len2, oneOf, ref, test, use, used
			ref = config.module.rules
			for (i = 0, len = ref.length; i < len; i++) {
				;({ test, oneOf } = ref[i])
				if (String(test) === String(/\.sass$/)) {
					for (j = 0, len1 = oneOf.length; j < len1; j++) {
						;({ use } = oneOf[j])
						for (k = 0, len2 = use.length; k < len2; k++) {
							used = use[k]
							if (used.loader === 'sass-loader') {
								used.options = {
									sassOptions: {
										indentedSyntax: true
									}
								}
							}
						}
					}
				}
			}
			return config
		})
	}
}.call(this))
