// Generated by CoffeeScript 2.5.0
import Vuex from 'vuex';

export default function(Vue, options, {appOptions}) {
  Vue.use(Vuex);
  Vue.prototype.$x = Vuex;
  return appOptions.vuex = new Vuex.Store(options);
};
