// Generated by CoffeeScript 2.4.1
import VueApollo from 'vue-apollo';

import ApolloClient from 'apollo-boost';

import 'isomorphic-fetch';

export default function(Vue, options, {appOptions}) {
  Vue.use(VueApollo);
  return appOptions.apolloProvider = new VueApollo({
    defaultClient: new ApolloClient(options)
  });
};
