// Generated by CoffeeScript 2.5.1
import VueApollo from 'vue-apollo';

import ApolloClient from 'apollo-boost';

import 'isomorphic-fetch';

import gql from 'graphql-tag';

export default function(Vue, options, {appOptions}) {
  Vue.use(VueApollo);
  appOptions.apolloProvider = new VueApollo({
    defaultClient: new ApolloClient(options)
  });
  return Vue.prototype.$gql = gql;
};
